// Fallback & seed data for client-side offline resilience and immediate UI hydration
// Ministry of Coal | SIH 2026 - Smart Compliance Monitoring

export const SAMPLE_MINES = [
  {
    id: "gevra",
    name: "Gevra Opencast Mine",
    subsidiary: "South Eastern Coalfields Limited (SECL)",
    state: "Chhattisgarh",
    lat: 22.336312,
    lng: 82.545748,
    capacity_mtpa: 70.0,
    production_mtpa: 55.8,
    ec_limit_mtpa: 70.0,
    opening_year: 1981,
    composite_risk_score: 52.4,
    risk_level: "ELEVATED",
    color: "#f59e0b",
    mine_type: "Opencast",
    contractor: "Contractor A (Heavy Earthmovers Ltd)",
    caaqms_station: "SECL GEVRA",
    safety_officer: "R. K. Sharma (Mine Manager - First Class)",
    worker_count: 3420,
    active_ptw_count: 8,
  },
  {
    id: "kusmunda",
    name: "Kusmunda Opencast Mine",
    subsidiary: "South Eastern Coalfields Limited (SECL)",
    state: "Chhattisgarh",
    lat: 22.332635,
    lng: 82.666666,
    capacity_mtpa: 75.0,
    production_mtpa: 50.1,
    ec_limit_mtpa: 62.5,
    opening_year: 1978,
    composite_risk_score: 64.1,
    risk_level: "ELEVATED",
    color: "#f59e0b",
    mine_type: "Opencast",
    contractor: "Contractor C (Eastern Mining Corp)",
    caaqms_station: "SECL Kusmunda AAQMS",
    safety_officer: "V. K. Patel (Safety Head - First Class)",
    worker_count: 2890,
    active_ptw_count: 12,
  },
  {
    id: "dipka",
    name: "Dipka Expansion Project",
    subsidiary: "South Eastern Coalfields Limited (SECL)",
    state: "Chhattisgarh",
    lat: 22.345077,
    lng: 82.544192,
    capacity_mtpa: 35.0,
    production_mtpa: 33.44,
    ec_limit_mtpa: 35.0,
    opening_year: 1990,
    composite_risk_score: 34.8,
    risk_level: "STABLE",
    color: "#10b981",
    mine_type: "Opencast",
    contractor: "Contractor A (Heavy Earthmovers Ltd)",
    caaqms_station: "M/s Dipka Expansion Project",
    safety_officer: "A. K. Mishra (Agent & GM)",
    worker_count: 2150,
    active_ptw_count: 6,
  },
  {
    id: "jayant",
    name: "Jayant Opencast Project",
    subsidiary: "Northern Coalfields Limited (NCL)",
    state: "Madhya Pradesh",
    lat: 24.1583,
    lng: 82.6546,
    capacity_mtpa: 30.0,
    production_mtpa: 30.0,
    ec_limit_mtpa: 30.0,
    opening_year: 1977,
    composite_risk_score: 41.2,
    risk_level: "STABLE",
    color: "#10b981",
    mine_type: "Opencast",
    contractor: "Contractor D (Vindhya Logistics)",
    caaqms_station: "AAQMS_NCL_JAYANT",
    safety_officer: "S. P. Singh (Mine Manager)",
    worker_count: 1980,
    active_ptw_count: 5,
  },
  {
    id: "nigahi",
    name: "Nigahi Opencast Project",
    subsidiary: "Northern Coalfields Limited (NCL)",
    state: "Madhya Pradesh",
    lat: 24.1350,
    lng: 82.599444,
    capacity_mtpa: 22.5,
    production_mtpa: 21.56,
    ec_limit_mtpa: 22.5,
    opening_year: 1985,
    composite_risk_score: 72.8,
    risk_level: "CRITICAL",
    color: "#ef4444",
    mine_type: "Opencast",
    contractor: "Contractor B (Apex Infrastructure & Logistics)",
    caaqms_station: "AAQMS_NCL_BINA / NCL_CETI",
    safety_officer: "M. K. Tiwari (Safety Officer)",
    worker_count: 2400,
    active_ptw_count: 9,
  },
  {
    id: "dudhichua",
    name: "Dudhichua Opencast Project",
    subsidiary: "Northern Coalfields Limited (NCL)",
    state: "Uttar Pradesh",
    lat: 24.16474,
    lng: 82.67287,
    capacity_mtpa: 25.5,
    production_mtpa: 9.27,
    ec_limit_mtpa: 25.5,
    opening_year: 1984,
    composite_risk_score: 58.2,
    risk_level: "ELEVATED",
    color: "#f59e0b",
    mine_type: "Opencast",
    contractor: "Contractor A (Heavy Earthmovers Ltd)",
    caaqms_station: "AAQMS_NCL_DUDHICHUA",
    safety_officer: "K. R. Verma (Project Officer)",
    worker_count: 1650,
    active_ptw_count: 4,
  },
  {
    id: "makardhokra",
    name: "Makardhokra-III (Dinesh) OC Mine",
    subsidiary: "Western Coalfields Limited (WCL)",
    state: "Maharashtra",
    lat: 20.8764,
    lng: 79.2235,
    capacity_mtpa: 4.0,
    production_mtpa: 3.5,
    ec_limit_mtpa: 4.0,
    opening_year: 2015,
    composite_risk_score: 16.5,
    risk_level: "STABLE",
    color: "#10b981",
    mine_type: "Opencast",
    contractor: "Contractor B (Apex Infrastructure & Logistics)",
    caaqms_station: "AAQMS_Makardhokra-III OC Mine",
    safety_officer: "G. D. Joshi (Safety Officer)",
    worker_count: 850,
    active_ptw_count: 3,
  },
  {
    id: "bhatadi",
    name: "Bhatadi Opencast Mine",
    subsidiary: "Western Coalfields Limited (WCL)",
    state: "Maharashtra",
    lat: 20.057380,
    lng: 79.267357,
    capacity_mtpa: 1.465,
    production_mtpa: 1.47,
    ec_limit_mtpa: 1.465,
    opening_year: 1997,
    composite_risk_score: 18.0,
    risk_level: "STABLE",
    color: "#10b981",
    mine_type: "Opencast",
    contractor: "Contractor E (Pragati Haulers)",
    caaqms_station: "Bhatadi Opencast Mine",
    safety_officer: "P. N. Rao (Manager)",
    worker_count: 420,
    active_ptw_count: 2,
  },
  {
    id: "basundhara_w",
    name: "Basundhara (W) Opencast Project",
    subsidiary: "Mahanadi Coalfields Limited (MCL)",
    state: "Odisha",
    lat: 22.059284,
    lng: 83.7304,
    capacity_mtpa: 5.0,
    production_mtpa: 1.43,
    ec_limit_mtpa: 5.0,
    opening_year: 2002,
    composite_risk_score: 21.5,
    risk_level: "STABLE",
    color: "#10b981",
    mine_type: "Opencast",
    contractor: "Contractor F (Utkal Mining Fleet)",
    caaqms_station: "Basundhara (W) OCP AAQMS",
    safety_officer: "S. K. Jena (Safety Head)",
    worker_count: 1120,
    active_ptw_count: 3,
  },
  {
    id: "lakhanpur",
    name: "Lakhanpur Opencast Project",
    subsidiary: "Mahanadi Coalfields Limited (MCL)",
    state: "Odisha",
    lat: 21.7451,
    lng: 83.8401,
    capacity_mtpa: 22.5,
    production_mtpa: 21.09,
    ec_limit_mtpa: 22.5,
    opening_year: 1995,
    composite_risk_score: 47.9,
    risk_level: "ELEVATED",
    color: "#f59e0b",
    mine_type: "Opencast",
    contractor: "Contractor B (Apex Infrastructure & Logistics)",
    caaqms_station: "Lakhanpur OCP AAQMS",
    safety_officer: "B. C. Sahoo (Manager)",
    worker_count: 1540,
    active_ptw_count: 5,
  },
  {
    id: "kulda",
    name: "Kulda Opencast Project",
    subsidiary: "Mahanadi Coalfields Limited (MCL)",
    state: "Odisha",
    lat: 22.033526,
    lng: 83.734846,
    capacity_mtpa: 16.8,
    production_mtpa: 14.78,
    ec_limit_mtpa: 16.8,
    opening_year: 2007,
    composite_risk_score: 32.1,
    risk_level: "STABLE",
    color: "#10b981",
    mine_type: "Opencast",
    contractor: "Contractor C (Eastern Mining Corp)",
    caaqms_station: "Kulda OCP AAQMS",
    safety_officer: "D. Mohanty (Agent)",
    worker_count: 1410,
    active_ptw_count: 4,
  },
  {
    id: "sonepur_bazari",
    name: "Sonepur Bazari Opencast Project",
    subsidiary: "Eastern Coalfields Limited (ECL)",
    state: "West Bengal",
    lat: 23.688231,
    lng: 87.223763,
    capacity_mtpa: 14.0,
    production_mtpa: 12.48,
    ec_limit_mtpa: 14.0,
    opening_year: 1995,
    composite_risk_score: 49.3,
    risk_level: "ELEVATED",
    color: "#f59e0b",
    mine_type: "Opencast",
    contractor: "Contractor E (Pragati Haulers)",
    caaqms_station: "AAQMS_ECL_SONEPUR_BAZARI",
    safety_officer: "T. K. Banerjee (Mine Manager)",
    worker_count: 1780,
    active_ptw_count: 6,
  },
];

export const SAMPLE_OBSERVATIONS = [
  {
    id: "OBS-2026-0901",
    mine_id: "gevra",
    mine_name: "Gevra Opencast Mine",
    inspector: "A. K. Verma (DGMS Bilaspur)",
    timestamp: "2026-09-08 09:30 IST",
    lat: 22.3368,
    lng: 82.5461,
    hazard_type: "Haul Road Berm Height Defect",
    severity: "Major",
    description: "Berm height along the main overburden haul road Bench #4 was found below tyre diameter (measured 1.1m vs required 1.8m).",
    action_required: "Construct compacted earthen berm of minimum 1.8m height prior to evening shift haulage.",
    status: "In Progress",
    deadline_hours: 24,
  },
  {
    id: "OBS-2026-0902",
    mine_id: "kusmunda",
    mine_name: "Kusmunda Opencast Mine",
    inspector: "Dr. S. Mukherjee (CPCB RO)",
    timestamp: "2026-09-07 14:15 IST",
    lat: 22.3331,
    lng: 82.6672,
    hazard_type: "Dust Suppression Failure at In-Pit Crusher",
    severity: "Critical",
    description: "Crusher hopper water spray nozzles choked; fugitive PM10 levels peaked above 160 ug/m3 in active loading zone.",
    action_required: "Immediate descaling of pressurized spray system and deployment of 2 additional mobile water mist cannons.",
    status: "Action Required",
    deadline_hours: 12,
  },
  {
    id: "OBS-2026-0903",
    mine_id: "nigahi",
    mine_name: "Nigahi Opencast Project",
    inspector: "R. C. Meena (Dy. Director Mines Safety)",
    timestamp: "2026-09-06 11:45 IST",
    lat: 24.1355,
    lng: 82.6001,
    hazard_type: "Tipper Reversing Radar Malfunction",
    severity: "Critical",
    description: "5 contractor tippers operated by Apex Infrastructure lacked operational Audio-Visual Alarm (AVAs) and proximity sensors.",
    action_required: "Ground non-compliant tippers immediately under Regulation 94 of CMR 2017.",
    status: "Pending Verification",
    deadline_hours: 6,
  },
];
